### ISSUE TITLE
Create index.html page

### ISSUE THREAD

**Issue by pjdicke** [pjdicke/static-media-app#1]
Lets start our collaboration but getting more familiar with git repos. This project will be our sandbox for building a static version of a simple media app.

Create a github account and send me your user name so I can add you to the project.

In order to use github you will need to insure you have a publich SSH Key linked to your account (https://help.github.com/articles/generating-an-ssh-key/).

Once you get your SSH key linked, clone the project down locally via git commands. `git clone git@github.com:pjdicke/static-media-app.git`

Create the first HTML page for the project, index.html
Insure it has a head with title and description as well as a body with "Hello World" as the content of the page.

Using git, stage the the files `git add .`, create a commit with meaningful message `git commit -m "INSERT MEANINGFUL MESSAGE"` and push the changes to the master branch `git push`.

Let me know which areas you need help with.

**Comment by 2magpies** [comment]
RE: HTML page...not sure about "description"...what is your expectation for that component? I went ahead and "committed" my attempt.

**Comment by 2magpies** [comment]
Ok, I added a description. I created a branch...not sure if that's the right thing to do. Do I need to merge that to the master?

**Comment by pjdicke** [comment]
Nailed it!

**Comment by 2magpies** [comment]
So, do I need to do a pull or commit or merge?
